# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sschwindt.github.io
title: GitHub
email: sschwindt [at] ucdavis.edu
author: Sebastian Schwindt
description: Welcome to my GitHub pages
copyright: 'Copyright &copy; 2019 Sebastian Schwindt. All Rights Reserved.'
credits: 'Credits: Thanks to all my supporters.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: google
    url: https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AJsN-F7OokulHdDmG3fYco8n1boS0Id9EUAGzPr4nwY775vpQx95fmIDlI7nrrPkL61BTGOntLflbQOEDmrwxkJdziG7K_lHkQ&user=GdmFKPgAAAAJ
  - title: home
    url: https://sebastian-schwindt.org
  - title: linkedin
    url: https://www.linkedin.com/in/sebastian-schwindt
